server:
  port: 8804
spring:
  application:
    name: foodie-admin
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true

ribbon:
  eager-load:
    enabled: true

# feign 配置服务间的连接时间和读取时间
feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 6000
  hystrix:
    enabled: false
  logging:
    level:
      com.*.facade.*: INFO

logging:
  level:
    com.alibaba.nacos.client.config.impl: WARN